# Generated by Django 2.1.1 on 2018-09-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_text', models.CharField(max_length=60)),
                ('apellido_text', models.CharField(max_length=60)),
                ('nacimiento_date', models.DateTimeField(verbose_name='fecha de nacimiento')),
                ('celular_text', models.CharField(max_length=15)),
            ],
        ),
    ]
